name: Build Dev Client
on:
    workflow_dispatch:
        inputs:
            platform:
                required: true
                description: 'Platform'
                type: choice
                options:
                    - all
                    - ios
                    - android
                default: 'all'
            profile:
                required: true
                description: 'Profile'
                type: choice
                options:
                    - development
                    - development-simulator
                default: 'development'
            clearCache:
                required: false
                description: 'Clear Cache'
                type: boolean
                default: false

jobs:
    build:
        name: Build DevClient
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-env
            - name: Set env
              run: |
                  echo "API_URL=${{ secrets.API_URL_DEV }}" >> $GITHUB_ENV
                  echo "APP_VARIANT=development" >> $GITHUB_ENV
            - name: Setup Expo
              uses: expo/expo-github-action@v8
              with:
                  expo-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Build
              run: |
                  npx --package eas-cli eas build \
                    --platform ${{ github.event.inputs.platform }} \
                    --profile ${{ github.event.inputs.profile }} \
                    ${{ (github.event.inputs.clearCache == 'true' && '--clear-cache') || '' }} \
                    --non-interactive \
                    --no-wait
